export const GET_ORIGIN = 'GET_ORIGIN';
export const GET_DESTINATION = 'GET_DESTINATION';
export const GET_ORIGIN_PREDICTION = 'GET_ORIGIN_PREDICTION';
export const GET_DESTINATION_PREDICTION = 'GET_DESTINATION_PREDICTION';
export const SET_PLACE_ID = 'SET_PLACE_ID';
export const SET_ORIGIN_PLACE_ID = 'SET_ORIGIN_PLACE_ID';
export const SET_DESTIN_PLACE_ID = 'SET_DESTIN_PLACE_ID';
